### Linear Regression

In [1]:
import numpy as np

In [2]:
#Parameters
inputDim = 3
inputCount = 100
alpha = 0.01

In [3]:
#x is dataset
x = np.random.rand(inputCount,inputDim)

In [4]:
#w is weight vector
w = np.random.rand((inputDim))
w

array([0.36095492, 0.29035001, 0.24341856])

In [5]:
# b is bias
b = np.random.rand()

In [6]:
# y is the label
y_ = np.random.rand(inputCount)

In [7]:
# adjust b in w itself 
w_new = np.hstack((w, b))
# adjust x with extra [1..1] column for x_n * b = b
ones_row =  np.ones(x.shape[0])
x_new = np.hstack((x, ones_row.reshape(-1,1)))

w_new

array([0.36095492, 0.29035001, 0.24341856, 0.95691796])

In [8]:
#Forward Propogation
y_hat = x_new@w_new
y_hat

array([1.41812384, 1.69065757, 1.48400842, 1.60875523, 1.34488728,
       1.22678022, 1.49040512, 1.2382097 , 1.5998947 , 1.42246035,
       1.5874279 , 1.51815463, 1.26226985, 1.39318358, 1.34113991,
       1.56690214, 1.24523323, 1.32186662, 1.59909427, 1.29096415,
       1.31918583, 1.40657014, 1.3541086 , 1.44483008, 1.18714402,
       1.53732406, 1.32478344, 1.51540567, 1.4584899 , 1.1920003 ,
       1.52329535, 1.40724058, 1.34517721, 1.41985626, 1.5084475 ,
       1.275092  , 1.17441098, 1.46716817, 1.29303132, 1.2351727 ,
       1.52680877, 1.35105683, 1.35133042, 1.26638194, 1.46086135,
       1.15212455, 1.46666528, 1.56590813, 1.51119923, 1.48754019,
       1.29964968, 1.24331568, 1.06601802, 1.20536505, 1.39928113,
       1.54388553, 1.13618079, 1.51659569, 1.57317203, 1.47568377,
       1.35370934, 1.33818799, 1.27652586, 1.44179518, 1.34838364,
       1.4853702 , 1.34240918, 1.17079367, 1.36427988, 1.47283687,
       1.27364828, 1.70213444, 1.41192813, 1.40642747, 1.45375

In [9]:
def MSE(w,x = x_new,y = y_):
    y_hat = x@w
    loss = np.sum(np.dot(y-y_hat,(y-y_hat).T))
    return loss

In [10]:
# w is row/col vector
def der(f_Rn_R,w):
    diagonal_elements = np.array([1e-6,1e-6,1e-6,1e-6])
    diagonal_matrix = np.diag(diagonal_elements) + w                            #SQUARE MATRIX
    f_x_h = np.apply_along_axis(f_Rn_R, axis=1, arr=diagonal_matrix)            #ROW MATRIX
    f_x = np.apply_along_axis(f_Rn_R, axis=1,arr = np.tile(w,(len(w),1))   )    #ROW MATRIX
    delta_w_L = ( f_x_h - f_x ) / diagonal_elements                             #ROW MATRIX
    return delta_w_L

In [11]:
delta_w_L = der(MSE,w_new)
delta_w_L

array([ 94.11349991,  78.01024137,  84.73514634, 175.63705686])

In [12]:
#Second way of getting delta_w_L
P = y_hat
delta_p_L = 2 * (P - y_)
delta_n_L = delta_p_L
delta_w_L_alt = x_new.T@delta_n_L
delta_w_L_alt

array([ 94.11346619,  78.01021378,  84.73511749, 175.63695687])

In [13]:
#Backward Propagation
w_new = w_new - alpha*delta_w_L_alt
w_new

array([-0.58017975, -0.48975213, -0.60393262, -0.79945161])