## Classification
### Single Class and MultiClass

In [114]:
import numpy as np

In [115]:
#Parameters
inputDim = 3
inputCount = 1000

In [116]:
x = np.random.rand(inputCount,inputDim)
#binary classification ( y = 0 or y = 1)
y = np.random.randint(2,size=(inputCount,))

In [117]:
w = np.random.rand(inputDim+1)

In [118]:
ones_row =  np.ones(x.shape[0])
x_new = np.hstack((x, ones_row.reshape(-1,1)))

In [119]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [120]:
y_hat = sigmoid(x_new@w)

In [121]:
import math as Math
def logLoss(w,x = x_new,y = y):
    #actually its cost

    y_hat = sigmoid((x@w).astype(float))
    y_hat_neg = 1 - y_hat
    loss = np.log((y_hat ** y) * (y_hat_neg ** (1-y)))
    cost = np.sum(loss)
    #loss_ = np.prod( )
    #cost_ = np.log( )
    return cost

In [122]:
logLoss(w)

-793.4319503522379

In [123]:
def der(f_Rn_R,w):
    diagonal_elements = np.random.rand(len(w)) * 1e-5
    diagonal_matrix = np.diag(diagonal_elements) + w                            #SQUARE MATRIX
    f_x_h = np.apply_along_axis(f_Rn_R, axis=1, arr=diagonal_matrix)            #ROW MATRIX
    f_x = np.apply_along_axis(f_Rn_R, axis=1,arr = np.tile(w,(len(w),1)))       #ROW MATRIX
    delta_w_L = ( f_x_h - f_x ) / diagonal_elements                             #ROW MATRIX
    return delta_w_L

In [124]:
delta_w_L = der(logLoss,w)
delta_w_L

array([-109.95122547, -107.80597493, -114.23949172, -212.95879759])

In [125]:
#another method to get delta_wL
delta_p_L = y - y_hat
delta_w_L_alt = x_new.T@delta_p_L

In [126]:
delta_w_L_alt

array([-109.95109859, -107.80570006, -114.23937173, -212.95826676])

In [133]:
#Multilabel Classification
classCount = 10
y2 = np.random.randint(classCount,size=(inputCount,))

In [136]:
w2 = np.random.rand(classCount,inputDim+1)
w2

array([[0.5032708 , 0.3302063 , 0.19733581, 0.3555817 ],
       [0.52411438, 0.80566605, 0.41713446, 0.92536099],
       [0.51517084, 0.71097415, 0.22926535, 0.85144108],
       [0.30450769, 0.96527485, 0.6189717 , 0.47871542],
       [0.40989169, 0.45641189, 0.34283655, 0.67734084],
       [0.80041731, 0.67832135, 0.31504948, 0.50363159],
       [0.44183073, 0.57440934, 0.18093254, 0.9353641 ],
       [0.18877688, 0.05259048, 0.42821611, 0.53806909],
       [0.33338735, 0.58195195, 0.31425391, 0.28399054],
       [0.71436671, 0.36662895, 0.93418445, 0.62196403]])

In [155]:
def oneHot_encoding(categories ,labels):
    num_samples = len(labels)
    num_categories = len(categories)
    one_hot = np.zeros((num_samples, num_categories))

    # Perform one-hot encoding
    for i, label in enumerate(labels):
        index = categories.index(label)
        one_hot[i, index] = 1
    return one_hot

In [156]:
y_encoded = oneHot_encoding([i for i in range(0,10)],y2)

In [157]:
y_encoded

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [161]:
import math as Math
def logLoss(w_dk,x = x_new,y_nk = y):
    #actually its cost
    y_hat = ((x@w_dk.T).astype(float))
    loss = y_nk * np.log(y_hat)
    cost = np.sum(loss)
    #loss_ = np.prod( )
    #cost_ = np.log( )
    return cost

In [162]:
logLoss(w,x_new,y_encoded)

59.04547232882163