In [67]:
import numpy as np

In [68]:
#Parameters
inputDim = 3
inputCount = 100

In [79]:
#x is dataset
x = np.random.randint(100,size=(inputCount,inputDim))

In [80]:
#w is weight vector
w = np.random.randint(100,size=(inputDim))

In [110]:
# b is bias
b = np.random.randint(100,size=1)

array([75])

In [112]:
y_hat = x@w + b

In [113]:
# y is the label
y = np.random.randint(100,size=(inputCount))

In [120]:
# adjust b in w itself 
w_new = np.hstack((w, b))
# adjust x with extra [1..1] column for x_n * b = b
ones_row =  np.ones(x.shape[0])
x_new = np.hstack((x, ones_row.reshape(-1,1)))


print(w_new)
print(x_new)

[ 9 51 45 75]
[[28.  0. 24.  1.]
 [40. 69. 55.  1.]
 [98. 87. 77.  1.]
 [92. 84.  1.  1.]
 [87. 52.  0.  1.]
 [ 3. 57. 12.  1.]
 [21. 24.  3.  1.]
 [ 9. 56. 65.  1.]
 [11. 25. 32.  1.]
 [51. 63. 38.  1.]
 [17. 10. 64.  1.]
 [44. 26. 10.  1.]
 [49. 40. 98.  1.]
 [41. 69. 81.  1.]
 [61. 72.  2.  1.]
 [95.  6. 47.  1.]
 [24.  5. 64.  1.]
 [22.  4. 75.  1.]
 [69. 11. 93.  1.]
 [ 6. 39.  0.  1.]
 [70. 35. 74.  1.]
 [67. 98. 82.  1.]
 [42. 78. 98.  1.]
 [58. 35. 44.  1.]
 [ 8. 96.  2.  1.]
 [87. 21. 92.  1.]
 [58. 39. 28.  1.]
 [48. 34. 62.  1.]
 [19. 11. 27.  1.]
 [72.  9. 64.  1.]
 [21. 41. 87.  1.]
 [87.  9. 82.  1.]
 [35. 31. 99.  1.]
 [36. 66. 70.  1.]
 [75. 39. 63.  1.]
 [67. 84. 66.  1.]
 [49. 90. 90.  1.]
 [49. 63. 53.  1.]
 [80. 75. 61.  1.]
 [66. 77. 12.  1.]
 [44. 95. 51.  1.]
 [84. 23. 59.  1.]
 [27. 21. 12.  1.]
 [29.  2. 35.  1.]
 [93.  3. 91.  1.]
 [58. 12. 56.  1.]
 [27. 11. 83.  1.]
 [98. 64. 20.  1.]
 [57. 87. 57.  1.]
 [59. 58. 54.  1.]
 [55. 98. 72.  1.]
 [81. 21. 37.  1.

In [141]:
def MSE(w,x = x_new,y = y):
    y_hat = x@w
    loss = np.sum(np.square(y-y_hat))
    return loss

In [169]:
def der(f_Rn_R,w):
    diagonal_elements = np.random.rand(len(w)) * 1e-5
    diagonal_matrix = np.diag(diagonal_elements) + w                            #SQUARE MATRIX
    f_x_h = np.apply_along_axis(f_Rn_R, axis=1, arr=diagonal_matrix)            #ROW MATRIX
    f_x = np.apply_along_axis(f_Rn_R, axis=1,arr = np.tile(w,(len(w),1)))       #ROW MATRIX
    delta_w_L = ( f_x_h - f_x ) / diagonal_elements                             #ROW MATRIX
    return delta_w_L
    

In [170]:
L = MSE
der(L,w_new)

array([53353728.93953045, 57361600.88119494, 60904935.33643652,
        1029666.04555207])

In [171]:
#cross check
del_L_w0= np.sum(2*((y-y_hat).T@x[:,0]))
del_L_w0

-53353726

In [217]:
import math as Math
def projectile_motion(v1):
    o,v0,t,g = v1
    f1 = v0*Math.cos(o)*t
    f2 = (v0*Math.sin(o)*t)-(1/2)*g*t**2
    return np.array([f1,f2])

In [218]:
import math as Math
def radius_xy(v1):
    r,o = v1
    x = r*Math.cos(o)
    y = r*Math.sin(o)
    return np.array([x,y])

In [219]:
def T_der(f_Rm_Rn,w):
    diagonal_elements = np.random.rand(len(w)) * 1                               #ROW MATRIX
    diagonal_matrix = np.diag(diagonal_elements) + w                                #SQUARE MATRIX
    f_x_h = np.apply_along_axis(f_Rm_Rn, axis=1, arr=diagonal_matrix)               # M*N MATRIX (  [[f1(w1+h),f2(w1+h)],[f1(w2+h),f2(w2+h)]]  )
    f_x = np.apply_along_axis(f_Rm_Rn, axis=1,arr = np.tile(w,(len(w),1)))          # M*N MATRIX (  [[f1(w1),f2(w1)],[f1(w2),f2(w2)]]  )
    delta_w_L = ( f_x_h - f_x ) / diagonal_elements[:, np.newaxis]                  # M*N MATRIX (  [[f1(w1+h)-f1(w1)/h1,f2(w1+h)-f2(w1)/h1],   ])
    return delta_w_L.T

In [222]:
L = projectile_motion
w = np.array([2,1.0472,3,4])
T_der(L,w)

array([[ 3210497.348045  , 16651123.38945163,  6250891.88423455,
         4482320.39504929],
       [  517101.8109526 ,  2681929.03642292,  1006805.85061841,
          721949.20047549],
       [ 1750034.57019715,  9076488.28363095,  3407346.49684001,
         2443302.32847339],
       [   37287.26330087,   193388.98456209,    72598.92355763,
           52058.43290007]])