In [2]:
import numpy as np

In [157]:
def Layer_matrixMult(x,w):
    #both w,x are row vectors
    return x@w.T

In [158]:
def Layer_biasAdd(N,b):
    #N is row vector and b is a scalar
    return N + b

In [159]:
def Layer_sigmoid(P):
    return 1 / 1 + np.exp(-P)

In [160]:
def Layer_softMax(Q):
    denom = np.sum(np.exp(Q))
    return Q / denom

In [216]:
def Layer_meanSqrLoss(P,y):
    #P, y both are row vector
        #returns loss_vector
    return ((np.sum( (P-y)**2 ))**(1/2)) / y.shape[0]

In [217]:
def Layer_crossEntropy(P,y):
    #y can be multiclass or singleclass
    #P,y both are row vectors
    #    or
    #P,y both are matrix of same shape
        # returns loss_vector
    if(len(y.shape) == 1):
        loss = np.log((P ** y) * ((1-P) ** (1-y)))
        return np.sum(loss)
    else:
        loss = np.log((P ** y))
        return np.sum(loss)

In [273]:
import pandas as pd
import sklearn.datasets as sk

In [219]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Prakhar\AppData\Local\Temp\ipykernel_28568\16828617.py:2: SyntaxWarning: invalid escape sequence '\s'
  raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)


In [220]:
data.shape

(506, 13)

In [221]:
target.shape

(506,)

In [232]:
def forwardProp(x,w,b,y):
    N = Layer_matrixMult(x,w)
    P = Layer_biasAdd(N,b)
    L = Layer_meanSqrLoss(P,y)
    print("Error:", L)
    return P

In [233]:
def backwardProp(x,P,y):
    delta_p_L = 2*(P - y)
    delta_n_L = delta_p_L
    delta_w_L = x.T@delta_n_L
    delta_b_L = (1/y.shape[0]) * np.sum( 2 * (y-P))
    return delta_w_L,delta_b_L

In [249]:
def stochastic_gd(x,w,b,y,alpha,epoch):
    for j in range(epoch):
        for i in range(len(y)):
            x_ar = x[i].reshape(1,-1)
            y_ar = np.array([y[i]])
            P = forwardProp(x_ar,w,b,y_ar)
            del_w,del_b = backwardProp(x_ar,P,y_ar)
            w = w - (del_w* alpha)
            b = b - (del_b* alpha)

In [250]:
w = np.random.rand(len(data[0]))
w.shape

(13,)

In [251]:
b = np.random.rand()
b

0.8227240932165103

In [261]:
alpha = 1e-9
epoch = 100

In [262]:
stochastic_gd(data,w,b,target,alpha,epoch)

Error: 648.8443073795182
Error: 599.9132727300577
Error: 574.0188302942478
Error: 553.5864479864484
Error: 557.1370512132363
Error: 562.8372201060471
Error: 662.4105553019306
Error: 673.5651438569552
Error: 681.3980407366389
Error: 666.7277498193573
Error: 680.8289683890234
Error: 672.2360661414867
Error: 648.7415735048274
Error: 647.5480053320108
Error: 642.9835162041016
Error: 644.3367637829467
Error: 622.0801081588755
Error: 650.4300028255897
Error: 538.5688739615043
Error: 646.5720573038483
Error: 653.1696395932172
Error: 654.6270086684862
Error: 666.5860173087719
Error: 668.0981578980079
Error: 662.4054276627296
Error: 576.6485753707822
Error: 642.4301995822617
Error: 579.8415612154511
Error: 651.0406112586662
Error: 638.153956325346
Error: 635.4313221594338
Error: 645.532311031796
Error: 515.5749797027046
Error: 630.7840460847332
Error: 530.5251047155114
Error: 621.4744779278341
Error: 600.8107122369224
Error: 608.8820501341262
Error: 598.5774592828149
Error: 614.8969809716697
Er

In [280]:
w

array([0.17204019, 0.66811544, 0.03091358, 0.4160439 , 0.13179944,
       0.68838708, 0.35620524, 0.12489679, 0.32723207, 0.86589223,
       0.01572767, 0.93697699, 0.56875774])

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [275]:
d = sk.load_iris()
x = d.data
y = d.target

In [276]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [277]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
def forwardProp(x,w,b,y):
    N = Layer_matrixMult(x,w)
    P = Layer_biasAdd(N,b)
    L = Layer_crossEntropy(P,y)
    print("Error:", L)
    return P

In [278]:
def backwardProp(x,P,y):
    delta_p_L = 2*(P - y)
    delta_n_L = delta_p_L
    delta_w_L = x.T@delta_n_L
    delta_b_L = (1/y.shape[0]) * np.sum( 2 * (y-P))
    return delta_w_L,delta_b_L

In [279]:
def oneHot_encoding(categories ,labels):
    num_samples = len(labels)
    num_categories = len(categories)
    one_hot = np.zeros((num_samples, num_categories))

    # Perform one-hot encoding
    for i, label in enumerate(labels):
        index = categories.index(label)
        one_hot[i, index] = 1
    return one_hot

In [285]:
y_encoded = oneHot_encoding([0,1,2],y)
y_encoded

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
def stochastic_gd(x,w,b,y,alpha,epoch):
    for j in range(epoch):
        for i in range(len(y)):
            x_ar = x[i].reshape(1,-1)
            y_ar = np.array([y[i]])
            P = forwardProp(x_ar,w,b,y_ar)
            del_w,del_b = backwardProp(x_ar,P,y_ar)
            w = w - (del_w* alpha)
            b = b - (del_b* alpha)