In [1]:
import numpy as np

In [2]:
def Layer_matrixMult(x,w):
    #both w,x are row vectors
    return x@w.T

In [3]:
def Layer_biasAdd(N,b):
    #N is row vector and b is a scalar
    return N + b

In [4]:
def Layer_sigmoid(P):
    return 1 / 1 + np.exp(-P)

In [5]:
def Layer_softMax(Q):
    denom = np.sum(np.exp(Q))
    return np.exp(Q) / denom

In [6]:
def Layer_meanSqrLoss(P,y):
    #P, y both are row vector
        #returns loss_vector
    return (np.sum( (P-y)**2 )) / y.shape[0]

In [7]:
def Layer_crossEntropy(P,y):
    #y can be multiclass or singleclass
    #P,y both are row vectors
    #    or
    #P,y both are matrix of same shape
        # returns loss_vector
    if(len(y.shape) == 1):
        loss = np.log((P ** y) * ((1-P) ** (1-y)))
        return np.sum(loss)
    else:
        loss = np.log((P ** y))
        return np.sum(loss) 

In [8]:
import pandas as pd
import sklearn.datasets as sk

In [9]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Prakhar\AppData\Local\Temp\ipykernel_14488\16828617.py:2: SyntaxWarning: invalid escape sequence '\s'
  raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
C:\Users\Prakhar\AppData\Local\Temp\ipykernel_14488\16828617.py:2: SyntaxWarning: invalid escape sequence '\s'
  raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)


EmptyDataError: No columns to parse from file

In [ ]:
data.shape

(506, 13)

In [ ]:
target.shape

(506,)

In [ ]:
def forwardProp(x,w,b,y):
    N = Layer_matrixMult(x,w)
    P = Layer_biasAdd(N,b)
    L = Layer_meanSqrLoss(P,y)
    print("Error:", L)
    return P

In [ ]:
def backwardProp(x,P,y):
    delta_p_L = 2*(P - y)
    delta_n_L = delta_p_L
    delta_w_L = x.T@delta_n_L
    delta_b_L = (1/y.shape[0]) * np.sum( 2 * (y-P))
    return delta_w_L,delta_b_L

In [ ]:
def stochastic_gd(x,w,b,y,alpha,epoch):
    for j in range(epoch):
        for i in range(len(y)):
            x_ar = x[i].reshape(1,-1)
            y_ar = np.array([y[i]])
            P = forwardProp(x_ar,w,b,y_ar)
            del_w,del_b = backwardProp(x_ar,P,y_ar)
            w = w - (del_w* alpha)
            b = b - (del_b* alpha)

In [ ]:
w = np.random.rand(len(data[0]))
w.shape

(13,)

In [ ]:
b = np.random.rand()
b

0.7806027627143808

In [ ]:
alpha = 1e-9
epoch = 100

In [ ]:
stochastic_gd(data,w,b,target,alpha,epoch)

Error: 106493.26839301286
Error: 99591.84637450195
Error: 84396.51025997526
Error: 79093.46966172763
Error: 80886.14572909074
Error: 85290.66136322104
Error: 108065.52061416881
Error: 116580.78026815277
Error: 121354.05191665124
Error: 114031.3446940418
Error: 122340.48379982202
Error: 116603.0552629894
Error: 97016.47029243948
Error: 101599.5997621969
Error: 104135.59015915025
Error: 99387.74751021907
Error: 85469.67548540843
Error: 106159.84293775301
Error: 57461.48467855953
Error: 102655.15912724103
Error: 110277.31826048357
Error: 109170.41725785437
Error: 115051.20078625057
Error: 117325.37582986103
Error: 114113.55953302844
Error: 78508.85557616023
Error: 104915.49556014925
Error: 79973.27859988478
Error: 109419.60725962896
Error: 102211.65253005484
Error: 102257.38358975037
Error: 109094.06188100185
Error: 56055.07127701018
Error: 101204.16531846524
Error: 63981.63546838408
Error: 99113.2780101114
Error: 89127.92054834719
Error: 89097.22156758429
Error: 82274.41335830496
Error: 

In [ ]:
w

array([0.29636886, 0.7604694 , 0.20191821, 0.34043767, 0.74298085,
       0.5570611 , 0.52581419, 0.29265819, 0.49890512, 0.1688268 ,
       0.26691242, 0.6069002 , 0.08416952])

In [10]:
d = sk.load_iris()
x = d.data
y = d.target

In [11]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
def oneHot_encoding(categories ,labels):
    num_samples = len(labels)
    num_categories = len(categories)
    one_hot = np.zeros((num_samples, num_categories))

    # Perform one-hot encoding
    for i, label in enumerate(labels):
        index = categories.index(label)
        one_hot[i, index] = 1
    return one_hot

In [14]:
y_encoded = oneHot_encoding([0,1,2],y)
y_encoded

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [15]:
def forwardProp(x,w,b,y):
    N = Layer_matrixMult(x,w)
    P = Layer_biasAdd(N,b)
    Q = Layer_softMax(P)
    L = Layer_crossEntropy(Q,y)
    print("Error:", L)
    return Q

In [16]:
w = np.random.rand(3,4)
b = np.random.rand(3)
w,b

(array([[0.46867576, 0.43208049, 0.15292328, 0.34008459],
        [0.86973158, 0.53324993, 0.82424748, 0.31462778],
        [0.59976325, 0.16575515, 0.71823145, 0.10975826]]),
 array([0.89269137, 0.80128339, 0.84408303]))

In [17]:
forwardProp(x,w,b,y_encoded)

Error: -1401.506942552946


array([[2.50362373e-06, 6.41081449e-05, 3.86091616e-06],
       [1.83668768e-06, 4.12643999e-05, 3.15211696e-06],
       [1.79562364e-06, 3.55265059e-05, 2.68975339e-06],
       [1.69191568e-06, 3.64095247e-05, 2.87641280e-06],
       [2.49447840e-06, 6.19869114e-05, 3.69693350e-06],
       [3.83844755e-06, 1.40469540e-04, 6.26235695e-06],
       [1.96246572e-06, 4.06030593e-05, 2.84460207e-06],
       [2.32322400e-06, 6.05033066e-05, 3.84270216e-06],
       [1.39154946e-06, 2.53254383e-05, 2.29703035e-06],
       [1.88222708e-06, 4.58001379e-05, 3.40585876e-06],
       [3.19009383e-06, 1.00541003e-04, 5.13360249e-06],
       [2.14794818e-06, 5.52117863e-05, 3.66213497e-06],
       [1.69399178e-06, 3.66555263e-05, 2.93621732e-06],
       [1.28001638e-06, 1.85306139e-05, 1.75377580e-06],
       [4.18400030e-06, 1.30472046e-04, 5.52879596e-06],
       [5.31815438e-06, 2.01882453e-04, 7.05486100e-06],
       [3.61068928e-06, 1.01017289e-04, 4.69859742e-06],
       [2.59023248e-06, 6.61572

In [ ]:
def backProp()