In [69]:
import numpy as np

In [70]:
def forward_layer_matrixMult(x, w):
    # both w,x are row vectors
    # x : n * d, w : d * 1
    # N = xw

    return x @ w

In [71]:
def backward_layer_matrixMult(x, w):
    # N = xw
    # dN/dw, dN/dx

    return x, w

In [72]:
def foraward_layer_biasAdd(N, b):
    # N : n * 1, b : n * 1
    # P = N + b

    return N + b

In [73]:
def backward_layer_biasAdd(N, b):
    # P = N + b (n * 1)
    # dP/dN = Identity (n * n)
    # dP/db = 1 (n * 1)

    return np.identity(N.shape[0]), np.ones((N.shape[0], 1))

In [74]:
def forward_layer_sigmoid(P):
    # Q = 1 / 1 + e^-P
    
    return 1 / (1 + np.exp(-P))

In [ ]:
def backward_layer_sigmoid(P):
    # dQ_i/dP_i = Q_i * (1 - Q_i)

    Q = forward_layer_sigmoid(P)
    Q1 = Q * (1 - Q)
    
    return np.diag(Q1)

In [75]:
def forward_layer_softMax(Q):
    denom = np.sum(np.exp(Q))
    return np.exp(Q) / denom

In [ ]:
def backward_layer_softMax():
    pass

In [76]:
def forward_layer_meanSqrLoss(P,y):
    # P : n * 1, y : n * 1
    # L = 1/n * sum((P - y) ^ 2)    : (1 * 1)
    
    return np.sum((P - y)**2)

In [99]:
def backward_layer_meanSqrLoss(P, y):
    # L = 1/n * sum((P - y) ^ 2)    : (1 * 1)
    # dL/dP = 2 * (P - y)   : (n * 1)

    return 2 * (P - y)

In [77]:
def forward_layer_crossEntropy(P,y):
    #y can be multiclass or singleclass
    #P,y both are row vectors
    #    or
    #P,y both are matrix of same shape
        # returns loss_vector
    if(len(y.shape) == 1):
        loss = np.log((P ** y) * ((1 - P) ** (1 - y)))
        return np.sum(loss)
    else:
        loss = np.log((P ** y))
        return np.sum(loss) 

In [ ]:
def backward_layer_crossEntropy(P, y):
    pass

In [78]:
import pandas as pd
import sklearn.datasets as sk

In [79]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [80]:
data.shape

(506, 13)

In [81]:
target.shape

(506,)

In [82]:
def forwardProp(x,w,b,y):
    N = Layer_matrixMult(x,w)
    P = Layer_biasAdd(N,b)
    L = Layer_meanSqrLoss(P,y)
    
    print("Error:", L)

    return P

In [83]:
def backwardProp(x,P,y):
    delta_p_L = 2 * (P - y)
    delta_n_L = delta_p_L
    delta_w_L = x.T @ delta_n_L
    delta_b_L = (1 / y.shape[0]) * np.sum(2 * (y - P))
    
    return delta_w_L, delta_b_L

In [84]:
def stochastic_gd(x,w,b,y,alpha,epoch):
    for j in range(epoch):
        i = np.random.randint(0, len(y))

        x_ar = x[i].reshape(1,-1)
        y_ar = np.array([y[i]])

        P = forwardProp(x_ar,w,b,y_ar)
        del_w, del_b = backwardProp(x_ar,P,y_ar)

        w = w - (del_w * alpha)
        b = b - (del_b * alpha)

In [85]:
w = np.random.rand(len(data[0]))
w.shape

(13,)

In [86]:
b = np.random.rand()
b

0.39698417158018384

In [87]:
alpha = 1e-9
epoch = 100

In [88]:
stochastic_gd(data,w,b,target,alpha,epoch)

Error: 445353.1064426412
Error: 162849.3842201956
Error: 198882.0354617045
Error: 170465.67277368606
Error: 176581.520528441
Error: 201224.34712635982
Error: 136716.9801063333
Error: 188496.9378558332
Error: 174982.6637392771
Error: 185955.82250035385
Error: 335642.12572308857
Error: 158839.6589377681
Error: 199325.3605952739
Error: 282245.3698029921
Error: 211497.32587049622
Error: 167382.48106834013
Error: 206630.52263566494
Error: 457612.0089775687
Error: 205680.44037008908
Error: 174610.8042426353
Error: 364692.9298063626
Error: 416718.36499488464
Error: 183859.99790087246
Error: 183279.03382232843
Error: 407069.3387203825
Error: 147458.0185989482
Error: 183268.88841206272
Error: 402383.538358546
Error: 258253.14698608356
Error: 188313.8421675916
Error: 389502.555881661
Error: 192585.3080884784
Error: 271857.5646487355
Error: 166503.2386544215
Error: 234009.03101747844
Error: 274119.90253700514
Error: 196795.0058627739
Error: 182763.22235766688
Error: 68823.53659434505
Error: 21332

In [89]:
w

array([0.80161162, 0.74577233, 0.59230341, 0.27961422, 0.19906403,
       0.10141362, 0.13709405, 0.65709816, 0.26577161, 0.48884179,
       0.96155476, 0.70327401, 0.8463903 ])

In [90]:
d = sk.load_iris()
x = d.data
y = d.target

In [91]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [92]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [93]:
def oneHot_encoding(categories ,labels):
    num_samples = len(labels)
    num_categories = len(categories)
    one_hot = np.zeros((num_samples, num_categories))

    # Perform one-hot encoding
    for i, label in enumerate(labels):
        index = categories.index(label)
        one_hot[i, index] = 1
    return one_hot

In [94]:
y_encoded = oneHot_encoding([0,1,2],y)
y_encoded

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [95]:
def forwardProp(x,w,b,y):
    N = Layer_matrixMult(x,w)
    P = Layer_biasAdd(N,b)
    Q = Layer_softMax(P)
    L = Layer_crossEntropy(Q,y)

    print("Error:", L)
    
    return Q

In [96]:
w = np.random.rand(3,4)
b = np.random.rand(3)
w, b

(array([[0.97058318, 0.65491429, 0.28608883, 0.82116954],
        [0.51095107, 0.79357168, 0.05205645, 0.74217778],
        [0.76039887, 0.17532465, 0.37859614, 0.58485675]]),
 array([0.38676294, 0.60145794, 0.94594029]))

In [97]:
forwardProp(x,w,b,y_encoded)

Error: -1247.9266708351126


array([[2.18180797e-04, 2.98968297e-05, 2.64761773e-05],
       [1.29508987e-04, 1.81519209e-05, 2.08322707e-05],
       [1.18156216e-04, 1.91077664e-05, 1.78433127e-05],
       [1.06343629e-04, 1.69463739e-05, 1.75275806e-05],
       [2.11401078e-04, 3.07538290e-05, 2.49715690e-05],
       [4.87127205e-04, 5.64028071e-05, 4.49272751e-05],
       [1.36545514e-04, 2.30378271e-05, 1.88591674e-05],
       [1.90830042e-04, 2.63773533e-05, 2.50414542e-05],
       [7.46617011e-05, 1.29869329e-05, 1.39959970e-05],
       [1.31070276e-04, 1.83406778e-05, 2.07679236e-05],
       [3.42438047e-04, 4.10568522e-05, 3.57764396e-05],
       [1.61721455e-04, 2.39392949e-05, 2.23385181e-05],
       [1.08264251e-04, 1.60140026e-05, 1.82101239e-05],
       [6.11577606e-05, 1.22114134e-05, 1.11139316e-05],
       [5.63953425e-04, 6.29155118e-05, 4.56255409e-05],
       [8.54007200e-04, 9.67546894e-05, 5.71173448e-05],
       [4.34453864e-04, 5.52404983e-05, 3.86136800e-05],
       [2.36853313e-04, 3.22001

In [98]:
def backProp(x, Q, y):
    delta_p_L = [[]]
    delta_w_L = x.T @ delta_p_L
    
    return delta_w_L, delta_b_L