In [3]:
import numpy as np

In [23]:
#Parameters
inputDim = 3
inputCount = 100
alpha = 0.01

In [24]:
#x is dataset
x = np.random.randint(100,size=(inputCount,inputDim))

In [25]:
#w is weight vector
w = np.random.randint(100,size=(inputDim))

In [26]:
# b is bias
b = np.random.randint(100)

In [27]:
# y is the label
y = np.random.randint(100,size=(inputCount))

In [28]:
# adjust b in w itself 
w_new = np.hstack((w, b))
# adjust x with extra [1..1] column for x_n * b = b
ones_row =  np.ones(x.shape[0])
x_new = np.hstack((x, ones_row.reshape(-1,1)))

In [29]:
#Forward Propogation
y_hat = x@w
y_hat

array([ 7796,  5418,  5828,  8617,  4207,  7935,  7478,  8533,  9990,
       15503,  6388, 14258, 11654,  8042,  4998, 13923, 12722,  7836,
       14348, 13095, 10415, 11093,  6081,  7030, 12200, 13986,  9530,
        4904, 10738,  6380,  8592, 13829,  6435,  4741, 10945, 12157,
        8892,  8049,  9220,  7268, 13504,  7154, 11432,  8641, 13263,
        6014, 12908, 12500,  7587,  3408,  5711,  9353,  5975,  9593,
        6840, 11469, 15130,  2739,  6873, 12791, 12591,  7569, 11509,
        5253,  9791,  8816,  8632, 12148, 12721, 10869, 12137,  1502,
       12685, 10381,  8250,  5606,  3215, 11270,  7233, 15143, 10493,
        6432,  8457, 13727,  8992,  5701,  8922,  7612, 15527,  8189,
        5170,  5972, 13382, 10441, 12405,  4632, 15064,  9819,  4387,
       12478])

In [30]:
def MSE(w,x = x_new,y = y):
    y_hat = x@w
    loss = np.sum(np.square(y-y_hat))
    return loss

In [31]:
def der(f_Rn_R,w):
    diagonal_elements = np.random.rand(len(w)) * 1e-5
    diagonal_matrix = np.diag(diagonal_elements) + w                            #SQUARE MATRIX
    f_x_h = np.apply_along_axis(f_Rn_R, axis=1, arr=diagonal_matrix)            #ROW MATRIX
    f_x = np.apply_along_axis(f_Rn_R, axis=1,arr = np.tile(w,(len(w),1)))       #ROW MATRIX
    delta_w_L = ( f_x_h - f_x ) / diagonal_elements                             #ROW MATRIX
    return delta_w_L

In [35]:
L = MSE
delta_w_L = der(L,w_new)
delta_w_L

array([1.06771261e+08, 9.60713166e+07, 9.22860106e+07, 1.86801624e+06])

In [36]:
#Second way of gettingg delta_w_L
P = y_hat
delta_p_L = 2 * (P - y)
delta_n_L = delta_p_L@np.identity(delta_p_L.shape[0])
delta_w_L_alt = x_new.T@delta_n_L
delta_w_L_alt

array([1.0580383e+08, 9.5097948e+07, 9.1414810e+07, 1.8482160e+06])

In [39]:
#Backward Propagation
w_new = w_new - alpha*delta_w_L_alt
w_new

array([-2115977.6 , -1901905.96, -1828254.2 ,   -36865.32])