In [110]:
import numpy as np

In [111]:
#Parameters
N = 1000
k = 5
n = 10
p = np.random.rand(k)
p

array([0.52350252, 0.45472014, 0.45830547, 0.92711887, 0.26315821])

In [112]:
pi = np.random.rand(k)
sum = np.sum(pi)
pi = pi/sum
pi = np.round(pi,decimals=2)
pi,np.sum(pi)

(array([0.11, 0.2 , 0.28, 0.21, 0.2 ]), 1.0)

In [113]:

datasample = []
for i in range(N):
    coin_c = np.random.randint(k)
    p_head = p[coin_c]
    sample_i = []
    for i in range(n):
        r = np.random.rand()
        if( r <= p_head):
            sample_i.append(1)
        else:
            sample_i.append(0)
    datasample.append(sample_i)


In [114]:
datasample

[[0, 0, 1, 0, 1, 1, 1, 1, 1, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 1, 1, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
 [0, 0, 1, 1, 0, 0, 0, 1, 1, 1],
 [0, 0, 0, 1, 1, 0, 0, 0, 1, 0],
 [1, 0, 0, 1, 0, 1, 1, 1, 1, 0],
 [1, 1, 0, 0, 1, 1, 1, 1, 0, 0],
 [0, 1, 1, 0, 0, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1, 0, 1, 0, 0],
 [1, 0, 1, 0, 1, 1, 0, 0, 0, 1],
 [1, 0, 1, 0, 1, 0, 0, 1, 1, 0],
 [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
 [0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
 [0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
 [1, 0, 1, 0, 1, 1, 0, 1, 0, 0],
 [0, 0, 1, 1, 0, 1, 1, 1, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [0, 1, 0, 1, 0, 0, 1, 0, 0, 0],
 [0, 0, 1, 0, 1, 0, 1, 0, 0, 1],
 [1, 0, 0, 1, 1, 0, 0, 1, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [0, 0, 0,

In [115]:
from math import comb
def E(p_approx,pi_approx):
    gamma = np.zeros((N,k))
    for i in range(0,N):
        xi = np.sum(datasample[i])
        sum = 0
        for c in range(0,k):
            gamma[i][c] = pi_approx[c] * comb(n,xi) * (p_approx[c]**xi) * ((1-p_approx[c])**(n-xi))
            sum += gamma[i][c]
        for c in range(0,k):
            gamma[i][c] = gamma[i][c]/sum
    return gamma

In [116]:
def M(gamma):   
    p_approx = np.zeros(k)
    pi_approx = np.zeros(k)
    for j in range(k):
        sum = 0
        for i in range(N):
            sum += gamma[i][j]
        pi_approx[j] = sum/N
    for r in range(k):
        sum = 0
        denom = 0
        for i in range(N):
            xi = np.sum(datasample[i])
            sum += gamma[i][r] * xi
            denom += gamma[i][r] * n
            p_approx[r] = sum/denom
    return p_approx,pi_approx

In [117]:
#Approximate Parameter
p_approx = np.random.rand(k)
pi_approx = np.random.rand(k)
pi_approx = pi_approx / np.sum(pi_approx)
pi_approx

array([0.32300222, 0.21831247, 0.10753487, 0.2641951 , 0.08695534])

In [118]:
def converge(p_approx,pi_approx):
    for i in range(1000):
        gamma = E(p_approx,pi_approx)
        p_old=  p_approx.copy()
        pi_old = pi_approx.copy()
        p_approx,pi_approx = M(gamma)
        if( np.sum((p_old - p_approx)**2) < 1e-5 and np.sum((pi_old - pi_approx)**2) < 1e-5):
            return p_approx,pi_approx
        

In [119]:
p_new,pi_new = converge(p_approx,pi_approx)

In [120]:

print("P MLE:",p_new)
print("Actual P:",p)

P MLE: [0.91984238 0.2213987  0.318598   0.5175746  0.4597524 ]
Actual P: [0.52350252 0.45472014 0.45830547 0.92711887 0.26315821]


In [121]:
print("Pi MLE",pi_new,"PI SUM:",np.sum(pi_approx))
print("Actual Pi:",pi)

Pi MLE [0.22559206 0.02055783 0.27527545 0.34089556 0.1376791 ] PI SUM: 1.0
Actual Pi: [0.11 0.2  0.28 0.21 0.2 ]
