In [3]:
import numpy as np

In [4]:
#Parameters
inputDim = 3
inputCount = 100

In [5]:
#x is dataset
x = np.random.randint(100,size=(inputCount,inputDim))

In [6]:
x

array([[77, 41, 17],
       [65, 50, 97],
       [ 3, 96, 29],
       [37, 52, 24],
       [25, 54, 15],
       [49, 80, 68],
       [78, 98, 28],
       [69, 55, 96],
       [ 3, 28, 87],
       [93, 93, 84],
       [70, 27, 85],
       [62, 47, 42],
       [57,  2, 65],
       [73, 73, 61],
       [27, 52, 83],
       [59, 58, 91],
       [39, 39, 32],
       [28,  4, 78],
       [77, 68, 75],
       [31, 10, 74],
       [77, 61, 29],
       [10, 29, 20],
       [86, 75, 87],
       [ 1, 84, 34],
       [90, 85, 72],
       [72,  1, 36],
       [75, 85, 88],
       [31, 32, 24],
       [10, 16, 76],
       [96, 59, 77],
       [92,  4, 29],
       [10, 39, 79],
       [31, 83, 48],
       [ 0, 82, 89],
       [27, 34, 45],
       [68, 15, 17],
       [57, 16, 73],
       [69, 16, 45],
       [81, 35, 79],
       [29,  9, 91],
       [72, 20, 91],
       [64, 87, 88],
       [11, 37, 76],
       [ 0, 15, 35],
       [47, 37, 17],
       [55, 49, 65],
       [86, 78, 33],
       [64, 5

In [7]:
#w is weight vector
w = np.random.randint(100,size=(inputDim))

In [8]:
w

array([78, 92, 23])

In [9]:
# b is bias
b = np.random.randint(100)

In [10]:
b

5

In [11]:
# @ is dot product (matrix multiplication)
# x(100 * 3) . w(3 * 1)
x@w 

array([10169, 11901,  9733,  8222,  7263, 12746, 15744, 12650,  4811,
       17742,  9899, 10126,  6125, 13813,  8799, 12031,  7366,  4346,
       13987,  5040, 12285,  3908, 15609,  8588, 16496,  6536, 15694,
        5914,  4000, 14687,  8211,  6185, 11158,  9591,  6269,  7075,
        7597,  7889, 11355,  5183,  9549, 15020,  6010,  2185,  7461,
       10293, 14643, 12099, 15452, 11563,  5738, 11382,  8058,  6568,
        6721,  8917,  3532,  3261,   538,  8742,  5279, 11182, 10508,
        7720,  3698,  8708, 14227, 10818, 10461,  8055, 12540, 17382,
        6384,  9401, 16637,  5543, 10758,  9593,  9506,  4873,  8178,
       12678,  2704,  5620, 12497, 11866, 15067,  2455, 15396,  6511,
        8518, 17285,  7209,  5536,  4317, 13225,  4517,  5883, 10604,
       13169])

In [12]:
y_hat = x@w + b

In [13]:
# y is the label
y = np.random.randint(100,size=(inputCount))

In [14]:
y

array([32, 88, 13, 54, 45, 79, 45, 30, 92, 85, 82, 93, 12, 96, 30, 25, 88,
       80,  1, 63, 32,  9, 48, 64, 43, 91, 72, 49, 44, 71, 76, 63, 24, 30,
       57, 38, 79, 71, 32, 35, 30, 62, 77, 10, 28,  2, 49, 20, 69, 73, 94,
       57, 24, 39,  9, 27, 17, 29, 28, 95, 95, 64, 65, 60, 59, 54, 65, 23,
       41, 11, 62, 71,  4, 63, 19, 36, 22, 56, 24, 83, 37, 21, 90, 96, 72,
        9, 15, 20, 89, 40, 79, 99, 44, 40, 30, 64,  0,  4, 17, 44])