In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Q5

#### (c)

In [13]:
# Newton's Method
# x_t+1 = x_t - f'x / f''x

dataset = np.array([[0,0],[1,3],[2,7],[3,-1],[4,0],[5,5],[6,10]])

A = np.hstack((np.ones((dataset.shape[0],1)), np.array([dataset[:,0]]).T, np.array([dataset[:,0]]).T**2, np.array([dataset[:,0]]).T**3))
A


array([[  1.,   0.,   0.,   0.],
       [  1.,   1.,   1.,   1.],
       [  1.,   2.,   4.,   8.],
       [  1.,   3.,   9.,  27.],
       [  1.,   4.,  16.,  64.],
       [  1.,   5.,  25., 125.],
       [  1.,   6.,  36., 216.]])

In [16]:
c = np.random.rand(4,1)
c

array([[0.18317471],
       [0.25053282],
       [0.867303  ],
       [0.1221224 ]])

In [24]:
Y = np.array([dataset[:,1]])
Y = Y.T
Y

array([[ 0],
       [ 3],
       [ 7],
       [-1],
       [ 0],
       [ 5],
       [10]])

In [26]:
def L_c(A,c,Y,lamda):
    return np.linalg.norm(A@c - Y, ord=None, axis=None, keepdims=False)**2 + np.linalg.norm(lamda*c, ord=None, axis=None, keepdims=False)**2

In [ ]:
def dL_c(A,lamda,c,Y):
    return 2*A.T@A@c - 2*A.T@Y + 2*lamda*c

In [25]:
def d2L_c(A,lamda):
    return A.T@A + lamda*np.identity(A.shape[0])