In [107]:
from sklearn.datasets import fetch_openml
import numpy as np
import matplotlib.pyplot as plt
mnist = fetch_openml('mnist_784')

d:\Anaconda\envs\ML_331\Lib\site-packages\sklearn\datasets\_openml.py:1002: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [90]:
x = mnist.data.values
x = x / 255
avg_x = np.zeros((x.shape[1]))
for i in range(x.shape[0]):
    avg_x += x[i]
avg_x /= x.shape[0]
for i in range(x.shape[0]):
    x[i] = x[i] - avg_x
x = x[0:10000,:]
x.shape

(10000, 784)

In [91]:
y = mnist.target.values
y

['5', '0', '4', '1', '9', ..., '2', '3', '4', '5', '6']
Length: 70000
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [92]:
y_new = []
for i in range(0,y.shape[0]):
    y_new.append(int(y[i]))
y = np.array(y_new)
y

array([5, 0, 4, ..., 4, 5, 6])

In [93]:
def Prob(x,mu):
    p = 1
    for i in range(0,x.shape[0]):
        p *= (mu[i] ** x[i])*(1- mu[i])**(1-x[i])
    return p

In [108]:
def E(p,pi):
    gamma = np.zeros((x.shape[0],pi.shape[0]))
    for i in range(0,x.shape[0]):
        for j in range(0,pi.shape[0]):
            gamma[i][j] = pi[j] * Prob(x[i], p[j])
        if(np.sum(gamma[i]) != 0):
            gamma[i] /= np.sum(gamma[i])
        else:
            gamma[i] = np.zeros(gamma[i].shape)
    return gamma

In [109]:
def M(gamma):
    pi = np.sum(gamma,axis=0)/x.shape[0]

    p = x.T @ gamma
    p = p.T

    n = p.T / (pi*x.shape[0])
    p = n.T
    
    return p, pi

In [110]:
p = np.random.rand(10,784)
pi = np.random.rand(10)
factor = 1/np.sum(pi)
pi = pi * factor
np.sum(pi)
p.shape

(10, 784)

In [112]:
for i in range(0,1):
    gamma = E(p,pi)
    p, pi  = M(gamma)

C:\Users\Prakhar\AppData\Local\Temp\ipykernel_24220\556516202.py:7: RuntimeWarning: invalid value encountered in divide
  n = p.T / (pi*x.shape[0])


((10, 784), (10,))

In [113]:
pi

array([0.0031715 , 0.        , 0.00189584, 0.02517625, 0.01951147,
       0.        , 0.00382705, 0.11957197, 0.28664592, 0.        ])

In [115]:
p

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [nan, nan, nan, ..., nan, nan, nan],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [nan, nan, nan, ..., nan, nan, nan]])

In [73]:
for mean in p:
    plt.imshow(mean.reshape(28,28), cmap = plt.cm.gray_r, interpolation='nearest')
    plt.show()

ValueError: cannot reshape array of size 3 into shape (28,28)